### ISSUE TITLE
Errors when applying a method to a route

### ISSUE THREAD

**Issue by fwgreen** [bjansen/gyokuro#12]
I get multiple errors using 0.2-dev and Ceylon 1.2.2 when applying a method to a route, including:  `Illegal annotation argument...` and `Type functions are not supported on the JVM`.

![screen shot 2016-08-28 at 7 22 32 pm](https://cloud.githubusercontent.com/assets/7098161/18037576/12c2ff02-6d56-11e6-91d5-a6a50ee93fbf.png)

**Comment by bjansen** [comment]
Make sure you're using `ceylon.net.http::post`, not `com.github.bjansen.gyokuro.core::post` ;)
