### ISSUE TITLE
Have users import their template library instead of providing it

### ISSUE THREAD

**Issue by fwgreen** [bjansen/gyokuro#14]
Providing an implementation of `TemplateRenderer` is helpful, but importing the template library might harm flexibility.  Mustache, for example, is at version 0.9.3 for Java 8 and 0.8.18 for Java 7.  A user might want the option to choose depending on requirements.

**Comment by bjansen** [comment]
So what you're saying is that I should only provide the `view.api` module, maybe give a few examples of implementations but not actually put them in modules and release them on Herd?

It could also be possible to override the imported module via an `overrides.xml`, or any new syntax that might come in the future.

**Comment by fwgreen** [comment]
It's great that you provide an implementation of the renderer:  Some users might not think to wrap the Ceylon collections as Java collections and get into trouble.  It's the import of the actually template library jar that, I believe, should be left to the user.

**Comment by bjansen** [comment]
Here are a few thoughts:

* `net.gyokuro.view.*` modules are convenient, and allow users to use a templating engine that Just Works™
* they are optional dependencies, so they don't clutter up `net.gyokuro.core`
* it's pretty easy to add an overrides file to use a different version of the engine than the one automatically pulled by these modules
* it's also easy to not import  any of those modules and instead define a custom `(Java)TemplateRenderer` or modify one of those provided by gyokuro

As a result, I think I'll keep existing modules as is, and make them import the latest version of each engine. That should cover most of the use-cases, while leaving users with reasonable alternatives.
