### ISSUE TITLE
Add support for path parameters

### ISSUE THREAD

**Issue by fwgreen** [bjansen/gyokuro#19]
Though not a standard *per se*, having URIs with required elements as path parameters could allow users to create cleaner APIs.  
```Ceylon
route("/home")
controller object userController {
    route("/{group}/users/{id}/scores")
    shared void showUserScores(String group, Integer id) {}
}
```

**Comment by bjansen** [comment]
How is that different from the first example at http://www.gyokuro.net/doc/0.2/#annotated-controllers ?

FTR more than one path parameter works as well:

```ceylon
    route("/:group/users/:id/scores")
    shared void showUserScores(String group, Integer id) {}
```

**Comment by fwgreen** [comment]
I didn't know that multiple parameters would work:  The example doesn't show it, so I assumed Gyokuro had the same limitation as Spark.  Thanks for the clarification 😄

**Comment by bjansen** [comment]
Right, I should clarify that. I've successfully used that feature on routes like:

```ceylon
route("/modules/:moduleName/comments/:commentId/edit")
```

**Comment by bjansen** [comment]
Done!
