### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by bjansen** [bjansen/gyokuro#2]
Possible API:

``` ceylon
ws("/websocket", (channel, message) => "Hello world");
```

See https://modules.ceylon-lang.org/repo/1/ceylon/net/1.2.0-3/module-doc/api/http/server/websocket/WebSocketEndpoint.type.html
See https://github.com/renatoathaydes/spark-ws

**Comment by renatoathaydes** [comment]
Make this a plugin or extension! So people don't get a whole bunch of WS dependencies to use the framework with pure HTTP, which is the huge majority...

**Comment by bjansen** [comment]
`ceylon.net` already supports websockets (via undertow), so I think it won't add any new dependency.

**Comment by renatoathaydes** [comment]
wow, ceylon.net really is bloated!
Jetty has some 5 jars or something for websocket support! but you need to specify explicitly you want to use them.

**Comment by fwgreen** [comment]
There might be a [minor issue](https://github.com/ceylon/ceylon-sdk/issues/485) implementing this feature.
